# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se', models.CharField(choices=[('S', 'Sale'), ('E', 'Expense')], max_length=1)),
                ('category', models.CharField(choices=[('S', 'Sale'), ('COGS', 'CostOfGoodsSold'), ('Sal', 'Salaries'), ('R', 'Rent')], max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
